<option value="Kab. Aceh Barat">Kab. Aceh Barat</option>
<option value="Kab. Aceh Barat Daya">Kab. Aceh Barat Daya</option>
<option value="Kab. Aceh Besar">Kab. Aceh Besar</option>
<option value="Kab. Aceh Jaya">Kab. Aceh Jaya</option>
<option value="Kab. Aceh Selatan">Kab. Aceh Selatan</option>
<option value="Kab. Aceh Singkil">Kab. Aceh Singkil</option>
<option value="Kab. Aceh Tamiang">Kab. Aceh Tamiang</option>
<option value="Kab. Aceh Tengah">Kab. Aceh Tengah</option>
<option value="Kab. Aceh Tenggara">Kab. Aceh Tenggara</option>
<option value="Kab. Aceh Timur">Kab. Aceh Timur</option>
<option value="Kab. Aceh Utara">Kab. Aceh Utara</option>
<option value="Kota Banda Aceh">Kota Banda Aceh</option>
<option value="Kab. Bener Meriah">Kab. Bener Meriah</option>
<option value="Kab. Bireuen">Kab. Bireuen</option>
<option value="Kab. Gayo Lues">Kab. Gayo Lues</option>
<option value="Kota Langsa">Kota Langsa</option>
<option value="Kota Lhokseumawe">Kota Lhokseumawe</option>
<option value="Kab. Nagan Raya">Kab. Nagan Raya</option>
<option value="Kab. Pidie">Kab. Pidie</option>
<option value="Kab. Pidie Jaya">Kab. Pidie Jaya</option>
<option value="Kota Sabang">Kota Sabang</option>
<option value="Kab. Simeulue">Kab. Simeulue</option>
<option value="Kota Subulussalam">Kota Subulussalam</option>
