<option value="Kab. Asmat">Kab. Asmat</option>
<option value="Kab. Biak Numfor">Kab. Biak Numfor</option>
<option value="Kab. Boven Digoel">Kab. Boven Digoel</option>
<option value="Kab. Deiyai">Kab. Deiyai</option>
<option value="Kab. Dogiyai">Kab. Dogiyai</option>
<option value="Kab. Intan Jaya">Kab. Intan Jaya</option>
<option value="Kab. Jayapura">Kab. Jayapura</option>
<option value="Kota Jayapura">Kota Jayapura</option>
<option value="Kab. Jayawijaya">Kab. Jayawijaya</option>
<option value="Kab. Keerom">Kab. Keerom</option>
<option value="Kab. Kepulauan Yapen">Kab. Kepulauan Yapen</option>
<option value="Kab. Lanny Jaya">Kab. Lanny Jaya</option>
<option value="Kab. Mamberamo Raya">Kab. Mamberamo Raya</option>
<option value="Kab. Mamberamo Tengah">Kab. Mamberamo Tengah</option>
<option value="Kab. Mappi">Kab. Mappi</option>
<option value="Kab. Merauke">Kab. Merauke</option>
<option value="Kab. Mimika">Kab. Mimika</option>
<option value="Kab. Nabire">Kab. Nabire</option>
<option value="Kab. Nduga">Kab. Nduga</option>
<option value="Kab. Paniai">Kab. Paniai</option>
<option value="Kab. Pegunungan Bintang">Kab. Pegunungan Bintang</option>
<option value="Kab. Puncak">Kab. Puncak</option>
<option value="Kab. Puncak Jaya">Kab. Puncak Jaya</option>
<option value="Kab. Sarmi">Kab. Sarmi</option>
<option value="Kab. Supiori">Kab. Supiori</option>
<option value="Kab. Tolikara">Kab. Tolikara</option>
<option value="Kab. Waropen">Kab. Waropen</option>
<option value="Kab. Yahukimo">Kab. Yahukimo</option>
<option value="Kab. Yalimo">Kab. Yalimo</option>
