<option value="Kab. Bengkalis">Kab. Bengkalis</option>
<option value="Kota Dumai">Kota Dumai</option>
<option value="Kab. Indragiri Hilir">Kab. Indragiri Hilir</option>
<option value="Kab. Indragiri Hulu">Kab. Indragiri Hulu</option>
<option value="Kab. Kampar">Kab. Kampar</option>
<option value="Kab. Kepulauan Meranti">Kab. Kepulauan Meranti</option>
<option value="Kab. Kuantan Singingi">Kab. Kuantan Singingi</option>
<option value="Kota Pekanbaru">Kota Pekanbaru</option>
<option value="Kab. Pelalawan">Kab. Pelalawan</option>
<option value="Kab. Rokan Hilir">Kab. Rokan Hilir</option>
<option value="Kab. Rokan Hulu">Kab. Rokan Hulu</option>
<option value="Kab. Siak">Kab. Siak</option>
