<option value="Kota Bau-Bau">Kota Bau-Bau</option>
<option value="Kab. Bombana">Kab. Bombana</option>
<option value="Kab. Buton">Kab. Buton</option>
<option value="Kab. Buton Utara">Kab. Buton Utara</option>
<option value="Kota Kendari">Kota Kendari</option>
<option value="Kab. Kolaka">Kab. Kolaka</option>
<option value="Kab. Kolaka Utara">Kab. Kolaka Utara</option>
<option value="Kab. Konawe">Kab. Konawe</option>
<option value="Kab. Konawe Selatan">Kab. Konawe Selatan</option>
<option value="Kab. Konawe Utara">Kab. Konawe Utara</option>
<option value="Kab. Muna">Kab. Muna</option>
<option value="Kab. Wakatobi">Kab. Wakatobi</option>
