<option value="Kab. Banggai">Kab. Banggai</option>
<option value="Kab. Banggai Kepulauan">Kab. Banggai Kepulauan</option>
<option value="Kab. Buol">Kab. Buol</option>
<option value="Kab. Donggala">Kab. Donggala</option>
<option value="Kab. Morowali">Kab. Morowali</option>
<option value="Kota Palu">Kota Palu</option>
<option value="Kab. Parigi Moutong">Kab. Parigi Moutong</option>
<option value="Kab. Parigi Moutong">Kab. Poso</option>
<option value="Kab. Sigi">Kab. Sigi</option>
<option value="Kab. Tojo Una-Una">Kab. Tojo Una-Una</option>
<option value="Kab. Toli-Toli">Kab. Toli-Toli</option>
