<option value="Kab. Agam">Kab. Agam</option>
<option value="Kota Bukittinggi">Kota Bukittinggi</option>
<option value="Kab. Dharmasraya">Kab. Dharmasraya</option>
<option value="Kab. Kepulauan Mentawai">Kab. Kepulauan Mentawai</option>
<option value="Kab. Lima Puluh Koto">Kab. Lima Puluh Koto</option>
<option value="Kota Padang">Kota Padang</option>
<option value="Kota Padang Panjang">Kota Padang Panjang</option>
<option value="Kab. Padang Pariaman">Kab. Padang Pariaman</option>
<option value="Kota Pariaman">Kota Pariaman</option>
<option value="Kab. Pasaman">Kab. Pasaman</option>
<option value="Kab. Pasaman Barat">Kab. Pasaman Barat</option>
<option value="Kota Payakumbuh">Kota Payakumbuh</option>
<option value="Kab. Pesisir Selatan">Kab. Pesisir Selatan</option>
<option value="Kota Sawah Lunto">Kota Sawah Lunto</option>
<option value="Kab. Sijunjung">Kab. Sijunjung</option>
<option value="Kab. Solok">Kab. Solok</option>
<option value="Kota Solok">Kota Solok</option>
<option value="Kab. Solok Selatan">Kab. Solok Selatan</option>
<option value="Kab. Tanah Datar">Kab. Tanah Datar</option>
